/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.2
 * Generated at: 2019-06-08 21:25:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://static.parastorage.com/services/santa-resources/resources/viewer/user-site-fonts/v7/languages.css\">\n");
      out.write("\n");
      out.write("<div id=\"content\">\n");
      out.write("    <style>\n");
      out.write("        .header {\n");
      out.write("            font: normal normal bold 60px/1.4em opensanshebrewcondensed-regular,sans-serif ;\n");
      out.write("            color:rgb(137, 173, 216);\n");
      out.write("            line-height: 1.1px;\n");
      out.write("            letter-spacing:0.1em;\n");
      out.write("            text-align: center;\n");
      out.write("            margin: 0 0 0 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .textbox {\n");
      out.write("            display:flex;\n");
      out.write("            margin: 25px 0 0 0;\n");
      out.write("        }\n");
      out.write("        .input-textbox {\n");
      out.write("            font:normal normal normal 14px/1.4em avenir-lt-w01_35-light1475496,sans-serif;\n");
      out.write("            border-style:solid;\n");
      out.write("            border-color:rgba(145, 145, 145, 1);\n");
      out.write("            margin: 0;\n");
      out.write("            flex:1;\n");
      out.write("        }\n");
      out.write("        .input-textbox::placeholder {color:#7F808A;}\n");
      out.write("        .input-textbox:hover {\n");
      out.write("            background-color:rgba(242, 250, 249, 1);\n");
      out.write("            border-color:rgba(82, 82, 82, 1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error {\n");
      out.write("            font:normal normal normal 15px/1.4em avenir-lt-w01_35-light1475496,sans-serif;\n");
      out.write("            color: rgb(255, 109, 109);\n");
      out.write("            margin: 0 0 0 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .button {\n");
      out.write("            background-color: rgb(137, 173, 216);\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("            padding: 8px 52px;\n");
      out.write("            margin: 25px;\n");
      out.write("            font:normal normal normal 15px/1.4em avenir-lt-w01_35-light1475496,sans-serif;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"layout\">\n");
      out.write("    <style>\n");
      out.write("        .container {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 1fr;\n");
      out.write("            height: 1000px;\n");
      out.write("            align-content: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .block {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"header block\">\n");
      out.write("            <h1>Login</h1>\n");
      out.write("        </div>\n");
      out.write("        <div>\n");
      out.write("            <form action=\"/login\" method=\"post\">\n");
      out.write("                <div class=\"block\">\n");
      out.write("                    <div class=\"textbox\" style=\"width:304px;height:43px;\">\n");
      out.write("                        <input type=\"text\" name=\"username\" style=\"padding-left:14px\" placeholder=\"username\" class=\"input-textbox\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"block\">\n");
      out.write("                    <div class=\"textbox\" style=\"width:304px;height:43px;\">\n");
      out.write("                        <input type=\"text\" name=\"password\" style=\"padding-left:14px\" placeholder=\"password\" class=\"input-textbox\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"block\">\n");
      out.write("                    <input type=\"submit\" class=\"button\" value=\"Login\"></input>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"error block\">\n");
      out.write("            <p> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
